blank_issues_enabled: true
contact_links:
  - name: inWind Translate Discord
    url: https://discord.gg/ej45e3PezJ
    about: Quick questions or support are often answered faster in Discord.
  - name: Official Website
    url: https://readfrog.app
    about: Learn more about inWind Translate and access docs and resources.
